language: ruby

before_install:
  - gem update --system '3.0.6'
  - gem i bundler -v '2.0.2'

bundler_args: --without benchmark --jobs=3 --retry=3

matrix:
  include:
    - rvm: 2.4.6
    - rvm: 2.5.5
    - rvm: 2.6.3
    - rvm: jruby-9.2.9.0
      env: JRUBY_OPTS=--debug
      jdk: openjdk8
    - rvm: ruby-head
    - rvm: 2.7.0-preview2
    - rvm: jruby-head
      env: JRUBY_OPTS=--debug
      jdk: openjdk8
  allow_failures:
    - rvm: 2.7.0-preview2
    - rvm: ruby-head
    - rvm: jruby-head
      env: JRUBY_OPTS=--debug
  fast_finish: true
