language: ruby

before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem i bundler -v '<2'

bundler_args: --without development --jobs=3 --retry=3

sudo: false

matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ruby_18.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/ruby_19.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/ruby_20.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/ruby_21.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: jruby-9.2.6.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ruby_22.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/jruby.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
