name: JRuby stable

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: openjdk:8

    strategy:
      matrix:
        ruby: [jruby-9.2.9.0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: gem i bundler

      - name: Install dependencies
        run:  bundle install --without benchmark --jobs=3 --retry=3

      - name: Run tests
        run: JRUBY_OPTS=--debug bundle exec rake
