name: JRuby stable

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: jruby:9.2

    steps:
      - uses: actions/checkout@v2

      - name: Install bundler
        run: gem i bundler

      - name: Install dependencies
        run:  bundle install --without benchmark --jobs=3 --retry=3

      - name: Run tests
        run: JRUBY_OPTS=--debug bundle exec rake
